/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista.ADMINISTRADOR;
import Vista.LoginORSignIn;
import javax.swing.JMenuItem;
import javax.swing.*;
import Model.Administrador;
import Vista.EdicionDatosPersonales;

/**
 *
 * @author wendellgonzalez
 */
public class ADMINGestiones extends javax.swing.JFrame {

    private Administrador administrador;
    
    /**
     * Creates new form ADMINGestiones
     */
    
    public ADMINGestiones(Administrador admin) {
        this.administrador = admin;
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        
        setTitle("ADMINISTRADOR: " + admin.getNombre());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnGestionEspecialidades = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnGestionUsuarios = new javax.swing.JButton();
        btnGestionSolicitudesMedicas = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "GESTIONES", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Helvetica Neue", 1, 24), new java.awt.Color(102, 102, 102))); // NOI18N
        jPanel1.setForeground(new java.awt.Color(51, 51, 51));

        btnGestionEspecialidades.setBackground(new java.awt.Color(0, 51, 51));
        btnGestionEspecialidades.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        btnGestionEspecialidades.setForeground(new java.awt.Color(255, 255, 255));
        btnGestionEspecialidades.setText("GESTION DE ESPECIALIDADES");
        btnGestionEspecialidades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGestionEspecialidadesActionPerformed(evt);
            }
        });

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMGS/hr-management.png"))); // NOI18N

        btnGestionUsuarios.setBackground(new java.awt.Color(0, 51, 51));
        btnGestionUsuarios.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        btnGestionUsuarios.setForeground(new java.awt.Color(255, 255, 255));
        btnGestionUsuarios.setText("GESTION DE USUARIOS");
        btnGestionUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGestionUsuariosActionPerformed(evt);
            }
        });

        btnGestionSolicitudesMedicas.setBackground(new java.awt.Color(0, 51, 51));
        btnGestionSolicitudesMedicas.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        btnGestionSolicitudesMedicas.setForeground(new java.awt.Color(255, 255, 255));
        btnGestionSolicitudesMedicas.setText("GESTION DE SOLICITUDES MEDICAS");
        btnGestionSolicitudesMedicas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGestionSolicitudesMedicasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(0, 363, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnGestionSolicitudesMedicas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnGestionEspecialidades, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnGestionUsuarios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(364, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(423, 423, 423)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnGestionUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnGestionEspecialidades, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnGestionSolicitudesMedicas, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(81, Short.MAX_VALUE))
        );

        jMenuBar1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "-", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Helvetica Neue", 0, 13), new java.awt.Color(204, 204, 204))); // NOI18N

        jMenu1.setText("MENÚ");

        jMenu1.setFont(new java.awt.Font("Helvetica Neue", java.awt.Font.BOLD, 15));

        JMenuItem itemCerrarSesion = new JMenuItem("Cerrar sesión");
        JMenuItem itemSalir = new JMenuItem("Salir del sistema");
        JMenuItem itemUpdateDatosPersonales = new JMenuItem("Editar Datos Personales");

        itemCerrarSesion.addActionListener(e -> {
            this.dispose();
            new LoginORSignIn().setVisible(true);
        });

        itemSalir.addActionListener(e -> {
            int resp = JOptionPane.showConfirmDialog(this, "¿Deseas salir del sistema?", "Confirmar Salida", JOptionPane.YES_NO_OPTION);
            if(resp == JOptionPane.YES_OPTION) {
                System.exit(0);
            }
        });

        itemUpdateDatosPersonales.addActionListener(e -> {
            new EdicionDatosPersonales(this.administrador).setVisible(true);
        });

        jMenu1.add(itemCerrarSesion);
        jMenu1.add(itemUpdateDatosPersonales);
        jMenu1.addSeparator();
        jMenu1.add(itemSalir);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGestionEspecialidadesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGestionEspecialidadesActionPerformed
        // TODO add your handling code here:
        if(administrador != null) {
        new GestionEspecialidades(this.administrador).setVisible(true);
        this.dispose();
        } else {
            JOptionPane.showMessageDialog(this, "Tipo de usuario no reconocido. No tiene acceso");
        }
    }//GEN-LAST:event_btnGestionEspecialidadesActionPerformed

    private void btnGestionUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGestionUsuariosActionPerformed
        // TODO add your handling code here:
        if(administrador != null) {
        new AdminRol(this.administrador).setVisible(true);
        this.dispose();
        } else {
            JOptionPane.showMessageDialog(this, "Tipo de usuario no reconocido. No tiene acceso");
        }
    }//GEN-LAST:event_btnGestionUsuariosActionPerformed

    private void btnGestionSolicitudesMedicasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGestionSolicitudesMedicasActionPerformed
        // TODO add your handling code here:
        if(administrador != null) {
            new GestionSolicitudesMedicas(this.administrador).setVisible(true);
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(this, "Tipo de usuario no reconocido. No tiene acceso");
        }
    }//GEN-LAST:event_btnGestionSolicitudesMedicasActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGestionEspecialidades;
    private javax.swing.JButton btnGestionSolicitudesMedicas;
    private javax.swing.JButton btnGestionUsuarios;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
