/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista.ADMINISTRADOR;

import DAO.MedicoDAO;
import DAOImpl.MedicoDAOImpl;
import Model.Administrador;
import Model.Medico;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.JMenuItem;
import javax.swing.*;
import Vista.LoginORSignIn;

/**
 *
 * @author wendellgonzalez
 */
public class GestionSolicitudesMedicas extends javax.swing.JFrame {

    private List<Medico> medicosEnEspera;
    private MedicoDAO medicoDAO;
    private Administrador admin;
    
    /**
     * Creates new form GestionSolicitudesMedicas
     */
    public GestionSolicitudesMedicas(Administrador admin) {
        this.admin = admin;
        this.medicoDAO = new MedicoDAOImpl();
        initComponents();
        setResizable(false);
        setLocationRelativeTo(null);
        setTitle("ADMINISTRADOR: " + admin.getNombre());
        
        cargarSolicitudes();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnAceptar = new javax.swing.JButton();
        btnRechazar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaSolicitudes = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "MANEJO DE SOLICITUDES", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Helvetica Neue", 1, 24), new java.awt.Color(0, 102, 102))); // NOI18N

        btnAceptar.setBackground(new java.awt.Color(0, 51, 51));
        btnAceptar.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        btnAceptar.setForeground(new java.awt.Color(255, 255, 255));
        btnAceptar.setText("ACEPTAR");
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });

        btnRechazar.setBackground(new java.awt.Color(0, 51, 51));
        btnRechazar.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        btnRechazar.setForeground(new java.awt.Color(255, 255, 255));
        btnRechazar.setText("RECHAZAR");
        btnRechazar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRechazarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(435, 435, 435)
                .addComponent(btnAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(btnRechazar, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRechazar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(38, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(0, 51, 51));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "GESTION DE SOLICITUDES MEDICAS", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Helvetica Neue", 1, 24), new java.awt.Color(255, 255, 255))); // NOI18N

        tablaSolicitudes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tablaSolicitudes);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1462, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 472, Short.MAX_VALUE)
        );

        jMenuBar1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "-", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Helvetica Neue", 0, 13), new java.awt.Color(204, 204, 204))); // NOI18N

        jMenu1.setText("MENÚ");

        jMenu1.setFont(new java.awt.Font("Helvetica Neue", java.awt.Font.BOLD, 15));

        JMenuItem itemCerrarSesion = new JMenuItem("Cerrar sesión");
        JMenuItem itemVolver = new JMenuItem("Volver al módulo anterior");
        JMenuItem itemSalir = new JMenuItem("Salir del sistema");

        itemCerrarSesion.addActionListener(e -> {
            this.dispose();
            new LoginORSignIn().setVisible(true);
        });

        itemVolver.addActionListener(e -> {
            this.dispose();
            new ADMINGestiones(this.admin).setVisible(true);
        });

        itemSalir.addActionListener(e -> {
            int resp = JOptionPane.showConfirmDialog(this, "¿Deseas salir del sistema?", "Confirmar Salida", JOptionPane.YES_NO_OPTION);
            if(resp == JOptionPane.YES_OPTION) {
                System.exit(0);
            }
        });

        jMenu1.add(itemCerrarSesion);
        jMenu1.add(itemVolver);
        jMenu1.addSeparator();
        jMenu1.add(itemSalir);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        // TODO add your handling code here:
        aceptarSolicitud();
    }//GEN-LAST:event_btnAceptarActionPerformed

    private void btnRechazarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRechazarActionPerformed
        // TODO add your handling code here:
        rechazarSolicitud();
    }//GEN-LAST:event_btnRechazarActionPerformed

    //Metodo para aceptar solicitud
    private void aceptarSolicitud() {
        int filaSeleccionada = tablaSolicitudes.getSelectedRow();
        if(filaSeleccionada >= 0) {
            Medico medicoSeleccionado = medicosEnEspera.get(filaSeleccionada);
            int respuesta = JOptionPane.showConfirmDialog(this, "¿Deseas aceptar la solicitud de " + medicoSeleccionado.getNombre() + "?", "Confirmar Aceptar", JOptionPane.YES_NO_OPTION);
            
            if(respuesta == JOptionPane.YES_OPTION) {
                boolean exito = medicoDAO.actualizarEstadoSolicitud(medicoSeleccionado.getIdMedico(), "ACEPTADO");
                if(exito) {
                    JOptionPane.showMessageDialog(this, "Solicitud aceptada correctamente.");
                    cargarSolicitudes();
                } else {
                    JOptionPane.showMessageDialog(this, "Error al aceptar la solicitud. ", "Error", JOptionPane.ERROR_MESSAGE);
                }
            }
        } else {
            JOptionPane.showMessageDialog(this, "Por favor, selecciona una solicitud de la tabla.");
        }
    }
    
    //Metodo para rechazar solicitud
    private void rechazarSolicitud() {
        int filaSeleccionada = tablaSolicitudes.getSelectedRow();
        if (filaSeleccionada >= 0) {
            Medico medicoSeleccionado = medicosEnEspera.get(filaSeleccionada);
            int respuesta = JOptionPane.showConfirmDialog(this, "¿Deseas rechazar la solicitud de " + medicoSeleccionado.getNombre() + "?", "Confirmar Rechazar", JOptionPane.YES_NO_OPTION);

            if (respuesta == JOptionPane.YES_OPTION) {
                boolean exito = medicoDAO.actualizarEstadoSolicitud(medicoSeleccionado.getIdMedico(), "RECHAZADO");
                if (exito) {
                    JOptionPane.showMessageDialog(this, "Solicitud rechazada correctamente.");
                    cargarSolicitudes();
                } else {
                    JOptionPane.showMessageDialog(this, "Error al rechazar la solicitud.", "Error", JOptionPane.ERROR_MESSAGE);
                }
            }
        } else {
            JOptionPane.showMessageDialog(this, "Por favor, selecciona una solicitud de la tabla.");
        }
    }
    
    //MEtodo para cargar Solicitudes en tabla
    private void cargarSolicitudes() {
        medicosEnEspera = medicoDAO.obtenerMedicosEnEspera();
        DefaultTableModel modelo = new DefaultTableModel(new Object[] {
        "ID", "NOMBRE", "EDAD", "EMAIL", "ESPECIALIDAD", "NUMERO DE COLEGIATURA", "FECHA GRADUACION", "AÑOS EXPERIENCIA", "ESTADO"
        }, 0 ) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        
        for(Medico medico : medicosEnEspera) {
            modelo.addRow(new Object[] {
                medico.getIdMedico(),
                medico.getNombre(),
                medico.getEdad(),
                medico.getEmail(),
                medico.getEspecialidad() != null ? medico.getEspecialidad().getNombre() : "N/A",
                medico.getNumeroColegiatura(), 
                medico.getFechaGraduacion(),
                medico.getAniosExperiencia(),
                medico.getEstadoSolicitud()
            });
        }
        tablaSolicitudes.setModel(modelo);
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnRechazar;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaSolicitudes;
    // End of variables declaration//GEN-END:variables
}
