/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista.MEDICOS;

import DAO.CitaDAO;
import DAOImpl.CitaDAOImpl;
import DAO.ConsultaDAO;
import DAOImpl.ConsultaDAOImpl;
import Model.Cita;
import Model.Medico;
import Model.ConsultaMedica;
import Model.Paciente;
import Model.Receta;
import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.JMenuItem;
import javax.swing.*;
import Vista.LoginORSignIn;
import Vista.MEDICOS.HistorialPorCita;

/**
 *
 * @author wendellgonzalez
 */
public class GestionConsultas extends javax.swing.JFrame {

    private Medico medicoLogueado;
    private Cita citaActual;
    private ConsultaDAO consultaDAO = new ConsultaDAOImpl();
    private CitaDAO citaDAO = new CitaDAOImpl();
    private List<Cita> listaCitasConfirmadas;
    private DefaultTableModel modeloRecetas;

    /**
     * Creates new form GestionConsultas
     *
     * @param cita
     * @param medico
     */
    public GestionConsultas(Cita cita, Medico medico) {
        this.citaActual = cita;
        this.medicoLogueado = medico;
        initComponents();
        setResizable(false);
        setLocationRelativeTo(null);
        setTitle("NOMBRE DEL MEDICO: " + medicoLogueado.getNombre());

        modeloRecetas = new DefaultTableModel();
        modeloRecetas.setColumnIdentifiers(new String[]{"Medicamento", "Dosis", "Frecuencia", "Duración"});
        tablaRecetas.setModel(modeloRecetas);

        lblPaciente.setText("Señor/a: " + citaActual.getPaciente().getNombre());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblPaciente = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDiagnostico = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtRecomendaciones = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        tablaRecetas = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        txtMedicamento = new javax.swing.JTextField();
        txtDosis = new javax.swing.JTextField();
        txtFrecuencia = new javax.swing.JTextField();
        txtDuracion = new javax.swing.JTextField();
        btnGuardar = new javax.swing.JButton();
        btnAgregar = new javax.swing.JButton();
        btnVerHistorialMedico = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "GESTION CONSULTAS", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Helvetica Neue", 1, 14), new java.awt.Color(0, 102, 102))); // NOI18N

        lblPaciente.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        lblPaciente.setForeground(new java.awt.Color(0, 102, 102));
        lblPaciente.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPaciente.setText("-----------------------");

        txtDiagnostico.setColumns(20);
        txtDiagnostico.setRows(5);
        txtDiagnostico.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "DIAGNOSTICO", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Helvetica Neue", 1, 14), new java.awt.Color(0, 102, 102))); // NOI18N
        jScrollPane1.setViewportView(txtDiagnostico);

        txtRecomendaciones.setColumns(20);
        txtRecomendaciones.setRows(5);
        txtRecomendaciones.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "RECOMENDACIONES", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Helvetica Neue", 1, 14), new java.awt.Color(0, 102, 102))); // NOI18N
        jScrollPane2.setViewportView(txtRecomendaciones);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(79, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(lblPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tablaRecetas.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        tablaRecetas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(tablaRecetas);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "RECETA Y CONSULTA", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Helvetica Neue", 1, 14), new java.awt.Color(0, 102, 102))); // NOI18N

        txtMedicamento.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        txtMedicamento.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "MEDICAMENTOS", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Helvetica Neue", 0, 14), new java.awt.Color(0, 102, 102))); // NOI18N

        txtDosis.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        txtDosis.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "DOSIS", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Helvetica Neue", 0, 14), new java.awt.Color(0, 102, 102))); // NOI18N

        txtFrecuencia.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        txtFrecuencia.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "FRECUENCIA", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Helvetica Neue", 0, 14), new java.awt.Color(0, 102, 102))); // NOI18N

        txtDuracion.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        txtDuracion.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "DURACION", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Helvetica Neue", 0, 14), new java.awt.Color(0, 102, 102))); // NOI18N

        btnGuardar.setBackground(new java.awt.Color(0, 51, 51));
        btnGuardar.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        btnGuardar.setForeground(new java.awt.Color(255, 255, 255));
        btnGuardar.setText("GUARDAR CONSULTA");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnAgregar.setBackground(new java.awt.Color(0, 51, 51));
        btnAgregar.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        btnAgregar.setForeground(new java.awt.Color(255, 255, 255));
        btnAgregar.setText("AGREGAR RECETA");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        btnVerHistorialMedico.setBackground(new java.awt.Color(102, 0, 0));
        btnVerHistorialMedico.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        btnVerHistorialMedico.setForeground(new java.awt.Color(255, 255, 255));
        btnVerHistorialMedico.setText("VER HISTORIAL MEDICO");
        btnVerHistorialMedico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerHistorialMedicoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(btnAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnVerHistorialMedico, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtMedicamento, javax.swing.GroupLayout.DEFAULT_SIZE, 505, Short.MAX_VALUE)
                            .addComponent(txtDosis)
                            .addComponent(txtFrecuencia)
                            .addComponent(txtDuracion))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(txtMedicamento, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtDosis, javax.swing.GroupLayout.DEFAULT_SIZE, 83, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(txtFrecuencia, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtDuracion, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnVerHistorialMedico, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(25, 25, 25))
        );

        jMenuBar1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "-", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Helvetica Neue", 0, 13), new java.awt.Color(204, 204, 204))); // NOI18N

        jMenu1.setText("MENÚ");

        jMenu1.setFont(new java.awt.Font("Helvetica Neue", java.awt.Font.BOLD, 13));
        JMenuItem itemCerrarSesion = new JMenuItem("Cerrar sesión");
        JMenuItem itemVolver = new JMenuItem("Volver al módulo anterior");
        JMenuItem itemSalir = new JMenuItem("Salir del sistema");

        itemCerrarSesion.addActionListener(e -> {
            this.dispose();
            new LoginORSignIn().setVisible(true);
        });

        itemVolver.addActionListener(e -> {
            this.dispose();
            new PanelMedicos(this.medicoLogueado).setVisible(true);
        });

        itemSalir.addActionListener(e -> {
            int resp = JOptionPane.showConfirmDialog(this, "¿Deseas salir del sistema?", "Confirmar Salida", JOptionPane.YES_NO_OPTION);
            if(resp == JOptionPane.YES_OPTION) {
                System.exit(0);
            }
        });

        jMenu1.add(itemCerrarSesion);
        jMenu1.add(itemVolver);
        jMenu1.addSeparator();
        jMenu1.add(itemSalir);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jScrollPane3)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 288, Short.MAX_VALUE)
                .addGap(5, 5, 5))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:
        GuardarConsulta();
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        // TODO add your handling code here:
        agregarReceta();
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnVerHistorialMedicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerHistorialMedicoActionPerformed
        // TODO add your handling code here:
        Paciente paciente = (Paciente) citaActual.getPaciente();
            HistorialPorCita historialFrame = new HistorialPorCita(paciente);
        if (citaActual != null && citaActual.getPaciente() != null) {
            historialFrame.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(this, "No hay datos de paciente para mostrar", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnVerHistorialMedicoActionPerformed

    //Metodo para agregar receta
    private void agregarReceta() {
        String medicamento = txtMedicamento.getText();
        String dosis = txtDosis.getText();
        String frecuencia = txtFrecuencia.getText();
        String duracion = txtDuracion.getText();
        String diagnostico = txtDiagnostico.getText();
        String recomendaciones = txtRecomendaciones.getText();

        if (diagnostico.isEmpty() || recomendaciones.isEmpty() || medicamento.isEmpty() || dosis.isEmpty() || frecuencia.isEmpty() || duracion.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Debe llenar los campos vacios", "Advertencia", JOptionPane.WARNING_MESSAGE);
            return;
        }

        modeloRecetas.addRow(new Object[]{medicamento, dosis, frecuencia, duracion});
    }

    // metodo para cuardar Consulta
    private void GuardarConsulta() {
        if (txtDiagnostico.getText().isEmpty() || txtRecomendaciones.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Por favor, complete el diagnóstico y las recomendaciones.", "Advertencia", JOptionPane.WARNING_MESSAGE);
            return;
        }

        ConsultaMedica consulta = new ConsultaMedica();
        consulta.setIdCita(citaActual.getIdCita());
        consulta.setIdPaciente(citaActual.getPaciente().getIdUsuario());
        consulta.setIdMedico(this.medicoLogueado.getIdUsuario());
        consulta.setDiagnostico(txtDiagnostico.getText());
        consulta.setRecomendaciones(txtRecomendaciones.getText());
        consulta.setFechaConsulta(LocalDateTime.now());

        List<Receta> listaRecetas = new ArrayList<>();
        for (int i = 0; i < modeloRecetas.getRowCount(); i++) {
            Receta receta = new Receta();
            receta.setMedicamento((String) modeloRecetas.getValueAt(i, 0));
            receta.setDosis((String) modeloRecetas.getValueAt(i, 1));
            receta.setFrecuencia((String) modeloRecetas.getValueAt(i, 2));
            receta.setDuracion((String) modeloRecetas.getValueAt(i, 3));
            listaRecetas.add(receta);
        }
        consulta.setRecetas(listaRecetas);

        if (consultaDAO.registrarConsulta(consulta)) {

            if (citaDAO.actualizarEstadoCita(citaActual.getIdCita(), "REALIZADA")) {
                JOptionPane.showMessageDialog(this, "Consulta y recetas guardadas exitosamente.");
            } else {
                JOptionPane.showMessageDialog(this, "Consulta guardada, pero hubo un error al actualizar el estado de la cita.", "Advertencia", JOptionPane.WARNING_MESSAGE);
            }

            this.dispose();

            new GestionCitasMedico(this.medicoLogueado).setVisible(true);

        } else {
            JOptionPane.showMessageDialog(this, "Error al guardar la consulta.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    private void limpiarCampos() {
        txtMedicamento.setText("");
        txtDiagnostico.setText("");
        txtDosis.setText("");
        txtDuracion.setText("");
        txtFrecuencia.setText("");
        txtRecomendaciones.setText("");
        txtDiagnostico.requestFocus();
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnVerHistorialMedico;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblPaciente;
    private javax.swing.JTable tablaRecetas;
    private javax.swing.JTextArea txtDiagnostico;
    private javax.swing.JTextField txtDosis;
    private javax.swing.JTextField txtDuracion;
    private javax.swing.JTextField txtFrecuencia;
    private javax.swing.JTextField txtMedicamento;
    private javax.swing.JTextArea txtRecomendaciones;
    // End of variables declaration//GEN-END:variables
}
